### ISSUE TITLE
I am having problems with my code

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/volunteer-form#1]
Markbot is asking for aria-label for my textarea but I don't know what that is

@thomasjbradley

**Comment by thomasjbradley** [comment]
It’s because you don’t have a `<label>` for your text area.

**Comment by fuen0015** [comment]
and for my legend can I remove the line by using css? for text decoration or did I do it wrong?

**Comment by thomasjbradley** [comment]
`text-decoration` only removes underlines. The line one the `<legend>` is a `border`.

**Comment by fuen0015** [comment]
for the smaller border at the bottom of each fieldset should I add a div and make a class?

**Comment by thomasjbradley** [comment]
I’m using an `<hr>` tag in this situation. It makes sense semantically because the `<hr>` represents a break in theme & content—there’s definitely a break in the theme of the questions.
